# Generated by Django 3.1.2 on 2020-10-22 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=20, verbose_name='客户名')),
                ('CustomerPhone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('CustomerAddress', models.CharField(max_length=50, verbose_name='地址')),
                ('CustomerCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('CustomerUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-CustomerCreated',),
            },
        ),
    ]
