# Generated by Django 3.1.2 on 2020-10-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommodityName', models.CharField(max_length=100, verbose_name='商品名称')),
                ('CommodityId', models.CharField(blank=True, max_length=50, verbose_name='商品编号')),
                ('CommodityPrice', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='商品价格')),
                ('CommodityDateTime', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('CommodityContent', models.TextField(blank=True, null=True, verbose_name='商品说明')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '所有商品',
                'ordering': ['-CommodityDateTime'],
            },
        ),
    ]
