# Generated by Django 3.1.2 on 2020-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_commoditypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditypost',
            name='CommondityImage',
            field=models.ImageField(blank=True, null=True, upload_to='commondity_img/%Y%m%d/', verbose_name='商品图片'),
        ),
    ]
