# Generated by Django 3.1.2 on 2020-10-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_commoditypost_commondityimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commoditypost',
            options={'ordering': ['-CommodityDateTime'], 'verbose_name': '商品', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='customerpost',
            options={'ordering': ('-CustomerCreated',), 'verbose_name': '客户', 'verbose_name_plural': '客户信息'},
        ),
        migrations.RemoveField(
            model_name='commoditypost',
            name='CommodityContent',
        ),
        migrations.AddField(
            model_name='commoditypost',
            name='CommodityNum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='商品数量'),
            preserve_default=False,
        ),
    ]
